name: Greeting on variable day

on:
  workflow_dispatch

env:
  DAY_OF_WEEK: Monday

# x gh secret set -r Zhengqbbb/img SuperSecret='Hello World!'
jobs:
  greeting_job:
    runs-on: ubuntu-latest
    env:
      Greeting: Hello
      SUPER_SECRET: ${{ secrets.SuperSecret }}
    steps:
      - name: "Say Hello Mona it's Monday"
        run: |
          [ "$SUPER_SECRET" = "Hello World!" ] || echo "no-eq"
          echo "111"