name: Use upload artifact
on:
  # push:
  workflow_dispatch:

jobs:
  Bundle:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    env:
      ___X_CMD_GHACTION_X: x1
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      ssh_key: ${{ secrets.SSH_PRIVATE_KEY }}
      git_user: zhengqbbb
      git_email: zqb@x-cmd.com
      CONCURRENCY: 10
    steps:
      - name: main
        uses: x-cmd/action@main
        with:
          code: x ws test || true
          artifact_name: artifact
          artifact_path: ~/work/action/action/ws/.artifact
